// apps/client/src/forms/LoginForm.vue
<script setup lang="ts">
import { useForm } from "vee-validate";
import { toTypedSchema } from "@vee-validate/zod";
import * as z from "zod";
import { useRouter } from "vue-router";

import { useAuthStore } from "@/store/AuthStore";

import { Button } from "@/components/ui/button";
import {
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Input } from "@/components/ui/input";
import Card from "@/components/ui/card/Card.vue";
import CardHeader from "@/components/ui/card/CardHeader.vue";
import CardTitle from "@/components/ui/card/CardTitle.vue";
import CardContent from "@/components/ui/card/CardContent.vue";
import apiClient from "@/api-client";
import { toast } from "vue-sonner";
import { stringRequiredMinCharacters } from "@/schemas/schema-utils";

const router = useRouter();
const { handleLogin } = useAuthStore();

const formSchema = toTypedSchema(
  z.object({
    username: stringRequiredMinCharacters("Nazwa użytkownika", 6),
    password: stringRequiredMinCharacters("Hasło", 6),
  })
);

const { isSubmitting, ...form } = useForm({
  validationSchema: formSchema,
});

const { mutate } = apiClient.login.useMutation({
  onSuccess: ({ body }) => {
    toast.success(
      "Udało się zalogować. Zostaniesz przeniesiony/a do ekranu głównego!"
    );
    handleLogin(body);
    form.handleReset();
    router.push("/dashboard");
  },
  onError: () => {
    toast.error("Wystąpił błąd podczas logowania!");
  },
});

const onSubmit = form.handleSubmit((values) => mutate({ body: values }));
</script>

<template>
  <Card class="mx-auto max-w-sm flex-1 flex flex-col justify-center gap-4">
    <CardHeader>
      <CardTitle class="text-2xl">Login</CardTitle>
    </CardHeader>
    <CardContent>
      <form @submit="onSubmit" class="flex flex-col gap-4">
        <FormField v-slot="{ componentField }" name="username">
          <FormItem>
            <FormLabel>Nazwa użytkownika</FormLabel>
            <FormControl>
              <Input type="text" placeholder="Nazwa użytkownika" v-bind="componentField" />
            </FormControl>
            <FormMessage />
          </FormItem>
        </FormField>
        <FormField v-slot="{ componentField }" name="password">
          <FormItem>
            <FormLabel>Hasło</FormLabel>
            <FormControl>
              <Input type="password" placeholder="******" v-bind="componentField" />
            </FormControl>
            <FormMessage />
          </FormItem>
        </FormField>
        <Button type="submit" :disabled="isSubmitting"> Zaloguj się </Button>
      </form>
    </CardContent>
  </Card>
</template>

// apps/client/src/components/LoginForm/index.tsx
"use client";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { toast } from "sonner";
import apiClient from "@/api-client";

import useAuth from "@/hooks/useAuth";

import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

import { loginFormSchema, TLoginFormInput } from "./schema";

const LoginForm = () => {
  const { setAuthData } = useAuth();

  const form = useForm<TLoginFormInput>({
    resolver: zodResolver(loginFormSchema),
    defaultValues: {
      username: "",
      password: "",
    },
  });

  const { mutate } = apiClient.login.useMutation({
    onSuccess: ({ body: { access_token, userId } }) => {
      setAuthData(access_token, userId);
      toast(
        "Udało się zalogować. Zostaniesz przeniesiony/a do ekranu głównego!"
      );
    },
    onError: () => {
      form.setError("root", {
        message:
          "Wystąpił błąd! Upewnij się, że podałeś/aś poprawny login i hasło",
      });
    },
  });

  const onSubmit = (values: TLoginFormInput): void => {
    form.clearErrors();
    mutate({ body: values });
  };

  return (
    <Card className="mx-auto max-w-sm flex-1">
      <CardHeader>
        <CardTitle className="text-2xl">Login</CardTitle>
      </CardHeader>
      <CardContent>
        <div className="grid gap-4">
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
              <FormField
                control={form.control}
                name="username"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Nazwa użytkownika</FormLabel>
                    <FormControl>
                      <Input placeholder="Nazwa użytkownika" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <FormField
                control={form.control}
                name="password"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Hasło</FormLabel>
                    <FormControl>
                      <Input placeholder="******" type="password" {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              {form.formState.errors.root && (
                <span className="text-red-600">
                  {form.formState.errors.root.message}
                </span>
              )}
              <Button type="submit" className="w-full">
                Zaloguj się
              </Button>
            </form>
          </Form>
        </div>
      </CardContent>
    </Card>
  );
};

export default LoginForm;
